version: "3.1"
services:
  cbws:
    build: .
    container_name: "cbws"
    command: python -m cbws.run
    ports:
      - "31415:31415"
    env_file:
      - '.env.docker'
    networks:
      - cloudbrain_network
networks:
  cloudbrain_network:
    external: true
